<?php require 'templates/header.phtml' ?>

<ul class="list-group">
<?php foreach($albums as $album): ?>
    <li class="list-group-item item-album">
        <div>
            <a href="detalle/<?= $album->Album_ID ?>">
                <b><?= $album->Nombre_Album ?></b> | <?= $album->Año ?> 
            </a>
        </div>
    </li>
<?php endforeach ?>
</ul>

<?php require 'templates/footer.phtml' ?>
