<form method="post" action="agregar_album">
    <label for="nombreAlbum">Nombre del Álbum:</label>
    <input type="text" id="nombre_album" name="nombre_album" required>

    <label for="anio">Año:</label>
    <input type="text" id="año" name="año" required>

    <label for="bandaId">ID de la Banda:</label>
    <input type="text" id="banda_id" name="banda_id" required>

    <input type="submit" value="Añadir Álbum">
</form>