<form method="post" action="ruta_a_tu_script_de_eliminacion.php">
    <label for="bandaId">Banda a eliminar:</label>
    <select id="bandaId" name="bandaId">
        <?php
        foreach ($bandas as $banda) {
            echo "<option value=\"" . $banda->Banda_ID . "\">" . $banda->Nombre_banda . "</option>";
        }
        ?>
    </select>

    <input type="submit" value="Eliminar Banda">
</form>
