<?php require 'templates/header.phtml' ?>

<div class="mt-5 w-25 mx-auto">
    <form method="POST" action="create_user_action"> <!-- Cambia el valor de action aquí -->
        <div class="form-group">
            <label for="usuario_name">Nombre de usuario</label>
            <input type="text" required class="form-control" id="usuario_name" name="usuario_name" aria-describedby="textHelp">
        </div>
        <div class="form-group">
            <label for="password">Contraseña</label>
            <input type="password" required class="form-control" id="password" name="password">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div> 
        <?php endif ?>
       
        <button type="submit" class="btn btn-primary mt-3">Crear usuario</button>
    </form>
</div>

<?php require 'templates/footer.phtml' ?>
